import { useEffect, useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { technicianOrderService } from '@/services/liverCare';
import type { LiverCareOrder } from '@/types/serviceOrder';
import type { FibroScanIntakeInput, PatientSex, ScanPatientIntake } from '@/types/scanPatientIntake';

interface TechnicianFibroScanIntakePanelProps {
  order: LiverCareOrder;
  paymentReady: boolean;
  visitReady: boolean;
  patientIntakeSubmitted: boolean;
  onUpdated: () => void;
}

function defaultFibroForm(intake: ScanPatientIntake | null): FibroScanIntakeInput {
  return {
    devicePatientCode: intake?.devicePatientCode ?? '',
    machinePatientName: intake?.machinePatientName ?? intake?.name ?? '',
    machinePatientAge: intake?.machinePatientAge ?? intake?.age ?? 0,
    machinePatientSex: intake?.machinePatientSex ?? intake?.sex ?? 'female',
    machinePatientPhone: intake?.machinePatientPhone ?? intake?.phone ?? '',
  };
}

export function TechnicianFibroScanIntakePanel({
  order,
  paymentReady,
  visitReady,
  patientIntakeSubmitted,
  onUpdated,
}: TechnicianFibroScanIntakePanelProps) {
  const [intake, setIntake] = useState<ScanPatientIntake | null>(null);
  const [form, setForm] = useState<FibroScanIntakeInput>(defaultFibroForm(null));
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = async () => {
    const row = await technicianOrderService.getPatientIntake(order.id);
    setIntake(row);
    setForm(defaultFibroForm(row));
  };

  useEffect(() => {
    void load();
  }, [order.id]);

  const run = async (action: () => Promise<unknown>) => {
    setSaving(true);
    setError(null);
    try {
      await action();
      await load();
      onUpdated();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Action failed');
    } finally {
      setSaving(false);
    }
  };

  if (!visitReady) {
    return (
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-base">2. FibroScan intake</CardTitle>
        </CardHeader>
        <CardContent className="py-4 text-sm text-muted-foreground">
          Complete patient details intake first, then enter FibroScan machine session details.
        </CardContent>
      </Card>
    );
  }

  if (!patientIntakeSubmitted) {
    return (
      <Card className="border-dashed">
        <CardHeader className="pb-2">
          <CardTitle className="text-base">2. FibroScan intake</CardTitle>
        </CardHeader>
        <CardContent className="py-4 text-sm text-muted-foreground">
          Submit patient details intake (step 1) before starting the FibroScan session.
        </CardContent>
      </Card>
    );
  }

  const submitted = Boolean(intake?.fibroscanIntakeSubmittedAt);
  const locked = submitted && intake?.fibroscanOperatorVerificationStatus !== 'rejected';

  return (
    <Card>
      <CardHeader className="pb-2">
        <div className="flex flex-wrap items-center gap-2">
          <CardTitle className="text-base">2. FibroScan intake</CardTitle>
          {submitted && <Badge variant="secondary">Submitted to operations</Badge>}
          {intake?.fibroscanOperatorVerificationStatus === 'approved' && (
            <Badge className="bg-emerald-600">Operator validated</Badge>
          )}
          {intake?.fibroscanOperatorVerificationStatus === 'rejected' && (
            <Badge variant="destructive">Rejected — update &amp; resubmit</Badge>
          )}
        </div>
        <CardDescription>
          After payment, enter patient name, age, sex &amp; phone on the scan machine. Copy the unique patient
          code generated by the device, then submit for operations to validate.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {error && <p className="text-sm text-destructive">{error}</p>}

        {!paymentReady && (
          <p className="rounded-md border border-amber-300 bg-amber-50 px-3 py-2 text-sm text-amber-900">
            Payment must be collected before starting the FibroScan session.
          </p>
        )}

        <div className="grid gap-3 sm:grid-cols-2">
          <div className="space-y-1 sm:col-span-2">
            <Label>Device patient code</Label>
            <Input
              value={form.devicePatientCode}
              disabled={locked}
              placeholder="e.g. FS-PRIYA-38"
              onChange={(e) => setForm({ ...form, devicePatientCode: e.target.value })}
            />
          </div>
          <div className="space-y-1">
            <Label>Name entered on machine</Label>
            <Input
              value={form.machinePatientName}
              disabled={locked}
              onChange={(e) => setForm({ ...form, machinePatientName: e.target.value })}
            />
          </div>
          <div className="space-y-1">
            <Label>Sex entered on machine</Label>
            <select
              className="flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm disabled:opacity-50"
              value={form.machinePatientSex}
              disabled={locked}
              onChange={(e) => setForm({ ...form, machinePatientSex: e.target.value as PatientSex })}
            >
              <option value="male">Male</option>
              <option value="female">Female</option>
              <option value="other">Other</option>
            </select>
          </div>
          <div className="space-y-1">
            <Label>Age entered on machine</Label>
            <Input
              inputMode="numeric"
              value={form.machinePatientAge}
              disabled={locked}
              onChange={(e) => setForm({ ...form, machinePatientAge: Number(e.target.value) || 0 })}
            />
          </div>
          <div className="space-y-1">
            <Label>Phone entered on machine</Label>
            <Input
              value={form.machinePatientPhone}
              disabled={locked}
              onChange={(e) => setForm({ ...form, machinePatientPhone: e.target.value })}
            />
          </div>
        </div>

        {(!submitted || intake?.fibroscanOperatorVerificationStatus === 'rejected') && (
          <Button
            size="sm"
            disabled={
              saving ||
              !paymentReady ||
              !form.devicePatientCode.trim() ||
              !form.machinePatientName.trim() ||
              !form.machinePatientPhone.trim() ||
              form.machinePatientAge < 1
            }
            onClick={() => run(() => technicianOrderService.submitFibroScanIntake(order.id, form))}
          >
            Submit FibroScan intake
          </Button>
        )}

        {submitted && intake?.fibroscanOperatorVerificationStatus === 'pending' && (
          <p className="text-sm text-emerald-700 dark:text-emerald-300">
            FibroScan intake submitted {new Date(intake.fibroscanIntakeSubmittedAt!).toLocaleString()}. You can
            start scanning while operations validates.
          </p>
        )}
      </CardContent>
    </Card>
  );
}
