import type { Enquiry } from '@/types/enquiry';
import type { LiverCareOrder, OrderTimelineEvent } from '@/types/serviceOrder';
import { buildSeedPackages } from './package.mock.seed';

const now = Date.now();
const days = (n: number) => new Date(now - n * 86400000).toISOString();

export const MOCK_PACKAGES = buildSeedPackages();

export const MOCK_ENQUIRIES: Enquiry[] = [
  {
    id: 'enq-1',
    enquiryNumber: 'ENQ-2026-0001',
    threadId: 'thread-9876543210',
    threadSequence: 1,
    source: 'website',
    patientName: 'Priya Sharma',
    phone: '9876543210',
    email: 'priya@example.com',
    age: 42,
    gender: 'female',
    city: 'Mumbai',
    address: 'Andheri West, Mumbai',
    preferredPackageId: 'pkg-2',
    preferredPackageCode: 'PKG-2',
    message: 'Interested in fibrosis scan package with blood test.',
    enquiryAt: days(2),
    assignedExecutiveId: 'ops-1',
    assignedExecutiveName: 'Operations Team',
    status: 'interested',
    followUpAt: new Date(now + 86400000).toISOString(),
    internalNotes: 'Called — wants home visit on weekend.',
    callRemarks: 'Reached, callback scheduled',
    followUpLogs: [
      {
        id: 'fu-enq1-1',
        status: 'new',
        internalNotes: 'Website enquiry received.',
        createdAt: days(2),
        createdByName: 'System',
      },
      {
        id: 'fu-enq1-2',
        status: 'contacted',
        callRemarks: 'Reached, callback scheduled',
        createdAt: days(1.5),
        createdByName: 'Operations Team',
      },
      {
        id: 'fu-enq1-3',
        status: 'interested',
        internalNotes: 'Called — wants home visit on weekend.',
        followUpAt: new Date(now + 86400000).toISOString(),
        createdAt: days(1),
        createdByName: 'Operations Team',
      },
    ],
    createdAt: days(2),
    updatedAt: days(1),
  },
  {
    id: 'enq-2',
    enquiryNumber: 'ENQ-2026-0002',
    threadId: 'thread-9123456780',
    threadSequence: 1,
    source: 'whatsapp',
    patientName: 'Rajesh Kumar',
    phone: '9123456780',
    email: null,
    age: 55,
    gender: 'male',
    city: 'Pune',
    preferredPackageId: 'pkg-1',
    preferredPackageCode: 'PKG-1',
    message: 'Need scan only, no blood test.',
    enquiryAt: days(1),
    status: 'new',
    createdAt: days(1),
    updatedAt: days(1),
  },
  {
    id: 'enq-3',
    enquiryNumber: 'ENQ-2026-0003',
    threadId: 'thread-9988776655',
    threadSequence: 1,
    source: 'manual',
    patientName: 'Anita Desai',
    phone: '9988776655',
    city: 'Bangalore',
    preferredPackageId: 'pkg-3',
    preferredPackageCode: 'PKG-3',
    enquiryAt: days(5),
    status: 'converted',
    patientId: 'demo-patient-1',
    orderId: 'lco-3',
    orderOutcome: 'confirmed',
    assignedExecutiveName: 'Operations Team',
    createdAt: days(5),
    updatedAt: days(3),
  },
  {
    id: 'enq-4',
    enquiryNumber: 'ENQ-2026-0004',
    threadId: 'thread-9988776655',
    threadSequence: 2,
    source: 'whatsapp',
    patientName: 'Anita Desai',
    phone: '9988776655',
    city: 'Bangalore',
    preferredPackageId: 'pkg-2',
    preferredPackageCode: 'PKG-2',
    message: 'Returned after last scan — wants PKG-2 this time for spouse check-up.',
    enquiryAt: days(0),
    status: 'new',
    patientId: 'demo-patient-1',
    assignedExecutiveName: 'Operations Team',
    createdAt: days(0),
    updatedAt: days(0),
  },
];

export const MOCK_LIVER_ORDERS: LiverCareOrder[] = [
  {
    id: 'lco-1',
    orderNumber: 'LFS-2026-0001',
    patientId: 'demo-patient-2',
    patientName: 'Rajesh Kumar',
    patientPhone: '9123456780',
    enquiryId: null,
    packageId: 'pkg-1',
    packageCode: 'PKG-1',
    packageName: 'Liver Fibrosis Scan',
    packagePrice: 5500,
    discount: 0,
    finalAmount: 5500,
    paymentMode: 'offline',
    paymentStatus: 'success',
    orderStatus: 'scan_completed',
    technicianId: 'tech-1',
    technicianName: 'Demo Technician',
    scanScheduledAt: days(1),
    createdBy: 'operations',
    createdAt: days(4),
    updatedAt: days(1),
  },
  {
    id: 'lco-2',
    orderNumber: 'LFS-2026-0002',
    patientId: 'demo-patient-3',
    patientName: 'Vikram Patel',
    patientPhone: '9012345678',
    packageId: 'pkg-2',
    packageCode: 'PKG-2',
    packageName: 'Liver Fibrosis Scan + Pathological Test',
    packagePrice: 8000,
    discount: 500,
    finalAmount: 7500,
    paymentMode: 'online_link',
    paymentStatus: 'success',
    orderStatus: 'final_report_generated',
    technicianId: 'tech-1',
    technicianName: 'Demo Technician',
    partnerLabId: 'lab-1',
    partnerLabName: 'Metro Diagnostics',
    scanScheduledAt: days(3),
    createdBy: 'operations',
    createdAt: days(7),
    updatedAt: days(1),
  },
  {
    id: 'lco-6',
    orderNumber: 'LFS-2026-0006',
    patientId: 'demo-patient-5',
    patientName: 'Kavita Nair',
    patientPhone: '9765432109',
    packageId: 'pkg-2',
    packageCode: 'PKG-2',
    packageName: 'Liver Fibrosis Scan + Pathological Test',
    packagePrice: 8000,
    discount: 0,
    finalAmount: 8000,
    paymentMode: 'offline',
    paymentStatus: 'success',
    orderStatus: 'lab_report_uploaded',
    technicianId: 'tech-1',
    technicianName: 'Demo Technician',
    partnerLabId: 'lab-2',
    partnerLabName: 'LifeCare Pathology',
    scanScheduledAt: days(2),
    createdBy: 'admin',
    createdAt: days(3),
    updatedAt: days(1),
  },
  {
    id: 'lco-5',
    orderNumber: 'LFS-2026-0005',
    patientId: 'demo-patient-4',
    patientName: 'Priya Sharma',
    patientPhone: '9876543210',
    enquiryId: 'enq-1',
    packageId: 'pkg-1',
    packageCode: 'PKG-1',
    packageName: 'Liver Fibrosis Scan',
    packagePrice: 5500,
    discount: 0,
    finalAmount: 5500,
    paymentMode: 'offline',
    paymentStatus: 'success',
    orderStatus: 'technician_assigned',
    technicianId: 'tech-1',
    technicianName: 'Demo Technician',
    scanScheduledAt: new Date(now + 3600000).toISOString(),
    createdBy: 'operations',
    createdAt: days(1),
    updatedAt: days(0),
  },
  {
    id: 'lco-4',
    orderNumber: 'LFS-2026-0004',
    patientId: '00000000-0000-4000-8000-000000000201',
    patientName: 'Rohan Mehta',
    patientPhone: '+919900000001',
    packageId: 'pkg-2',
    packageCode: 'PKG-2',
    packageName: 'Liver Fibrosis Scan + Pathological Test',
    packagePrice: 8000,
    discount: 0,
    finalAmount: 7500,
    paymentMode: null,
    paymentStatus: 'pending',
    orderStatus: 'payment_pending',
    createdBy: 'operations',
    createdAt: days(0),
    updatedAt: days(0),
  },
  {
    id: 'lco-3',
    orderNumber: 'LFS-2026-0003',
    patientId: 'demo-patient-1',
    patientName: 'Anita Desai',
    patientPhone: '9988776655',
    enquiryId: 'enq-3',
    packageId: 'pkg-3',
    packageCode: 'PKG-3',
    packageName: 'Liver Fibrosis Scan + Pathological Test + Doctor Consultation Video',
    packagePrice: 9500,
    discount: 0,
    finalAmount: 9500,
    paymentMode: 'patient_portal',
    paymentStatus: 'success',
    orderStatus: 'consultation_pending',
    technicianId: 'tech-1',
    technicianName: 'Demo Technician',
    partnerLabId: 'lab-1',
    partnerLabName: 'Metro Diagnostics',
    doctorId: 'doc-1',
    doctorName: 'Dr. Meera Iyer',
    scanScheduledAt: days(5),
    consultationScheduledAt: new Date(now + 2 * 86400000).toISOString(),
    createdBy: 'admin',
    createdAt: days(10),
    updatedAt: days(1),
  },
];

export const MOCK_PATIENT_PORTAL_PHONE = '9900000001';

export const MOCK_ORDER_TIMELINES: Record<string, OrderTimelineEvent[]> = {
  'lco-5': [
    { id: 'tl-16', orderId: 'lco-5', eventType: 'order_created', label: 'Order created', category: 'order', performedBy: 'operations', detail: 'PKG-1 · ₹5,500', occurredAt: days(1) },
    { id: 'tl-17', orderId: 'lco-5', eventType: 'payment_completed', label: 'Payment received', category: 'payment', performedBy: 'operations', detail: '₹5,500 via UPI · Ref UPI88231', occurredAt: days(1) },
    { id: 'tl-18', orderId: 'lco-5', eventType: 'assign_technician', label: 'Technician assigned', category: 'scan', performedBy: 'operations', detail: 'Assigned to Demo Technician', occurredAt: days(0) },
  ],
  'lco-4': [
    { id: 'tl-14', orderId: 'lco-4', eventType: 'order_created', label: 'Order created', category: 'order', performedBy: 'operations', detail: 'PKG-2 · ₹7,500', occurredAt: days(0) },
    { id: 'tl-15', orderId: 'lco-4', eventType: 'payment_link_sent', label: 'Payment link sent', category: 'payment', performedBy: 'operations', detail: '₹7,500 · Sent via whatsapp, sms, email', occurredAt: days(0) },
  ],
  'lco-1': [
    { id: 'tl-1', orderId: 'lco-1', eventType: 'order_created', label: 'Order created', category: 'order', performedBy: 'operations', detail: 'PKG-1 · ₹5,500', occurredAt: days(4) },
    { id: 'tl-2', orderId: 'lco-1', eventType: 'payment_completed', label: 'Payment received', category: 'payment', performedBy: 'operations', detail: '₹5,500 via cash', occurredAt: days(4) },
    { id: 'tl-3', orderId: 'lco-1', eventType: 'assign_technician', label: 'Technician assigned', category: 'scan', performedBy: 'operations', detail: 'Assigned to Demo Technician', occurredAt: days(3) },
    { id: 'tl-3b', orderId: 'lco-1', eventType: 'scan_data_fetched', label: 'Scan data fetched from device', category: 'scan', performedBy: 'technician', detail: 'LSM 6.2 kPa · CAP 248 dB/m · F2', occurredAt: days(2) },
    { id: 'tl-4', orderId: 'lco-1', eventType: 'scan_completed', label: 'Fibrosis scan completed', category: 'scan', performedBy: 'technician', detail: 'Scan data locked for report generation', occurredAt: days(1) },
  ],
  'lco-2': [
    { id: 'tl-5', orderId: 'lco-2', eventType: 'order_created', label: 'Order created', category: 'order', performedBy: 'operations', detail: 'PKG-2 · ₹7,500', occurredAt: days(7) },
    { id: 'tl-6', orderId: 'lco-2', eventType: 'payment_completed', label: 'Payment received', category: 'payment', performedBy: 'patient', detail: '₹7,500 via patient portal · UPI', occurredAt: days(6) },
    { id: 'tl-7', orderId: 'lco-2', eventType: 'scan_completed', label: 'Fibrosis scan completed', category: 'scan', performedBy: 'technician', detail: 'LSM 5.8 kPa · stage F1', occurredAt: days(4) },
    { id: 'tl-7b', orderId: 'lco-2', eventType: 'lab_assigned', label: 'Partner lab assigned', category: 'pathology', performedBy: 'operations', detail: 'Metro Diagnostics · Mumbai', occurredAt: days(4) },
    { id: 'tl-8', orderId: 'lco-2', eventType: 'lab_report_uploaded', label: 'Lab report uploaded', category: 'pathology', performedBy: 'operations', detail: 'liver-panel-rohan.pdf from reports@metrodiag.in', occurredAt: days(3) },
    { id: 'tl-9', orderId: 'lco-2', eventType: 'ai_extraction', label: 'AI pathology extraction completed', category: 'ai', performedBy: 'system', detail: '18 pathology fields extracted and saved for review', occurredAt: days(2) },
  ],
  'lco-3': [
    { id: 'tl-10', orderId: 'lco-3', eventType: 'enquiry_received', label: 'Enquiry received', category: 'order', performedBy: 'system', detail: 'Website enquiry · PKG-3 preferred', occurredAt: days(10) },
    { id: 'tl-11', orderId: 'lco-3', eventType: 'order_created', label: 'Order created', category: 'order', performedBy: 'operations', detail: 'PKG-3 · ₹9,500', occurredAt: days(9) },
    { id: 'tl-11b', orderId: 'lco-3', eventType: 'payment_completed', label: 'Payment received', category: 'payment', performedBy: 'operations', detail: '₹9,500 via bank transfer', occurredAt: days(8) },
    { id: 'tl-12', orderId: 'lco-3', eventType: 'final_report_generated', label: 'Final report generated', category: 'report', performedBy: 'operations', detail: 'RPT-2026-0003 v1 · Combined scan + pathology', occurredAt: days(3) },
    { id: 'tl-13', orderId: 'lco-3', eventType: 'assign_doctor', label: 'Doctor assigned', category: 'consultation', performedBy: 'operations', detail: 'Assigned to Dr. Meera Iyer', occurredAt: days(2) },
  ],
};

let enquirySeq = 5;
let orderSeq = MOCK_LIVER_ORDERS.length + 1;

export function nextEnquiryNumber(): string {
  const n = enquirySeq++;
  return `ENQ-2026-${String(n).padStart(4, '0')}`;
}

export function nextOrderNumber(): string {
  const n = orderSeq++;
  return `LFS-2026-${String(n).padStart(4, '0')}`;
}
