import type { PartnerLab } from '@/types/partnerLab';
import type { LabReportUpload } from '@/types/labReport';
import type { AIExtractionJob } from '@/types/aiExtraction';
import type { SampleDispatch } from '@/types/sampleDispatch';

const now = Date.now();
const days = (n: number) => new Date(now - n * 86400000).toISOString();

export const MOCK_PARTNER_LABS: PartnerLab[] = [
  {
    id: 'lab-1',
    name: 'Metro Diagnostics',
    contactPerson: 'Dr. Sanjay Rao',
    phone: '9876500001',
    email: 'reports@metrodiag.test',
    address: 'Andheri Kurla Road',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400069',
    gstNumber: '27AABCM1234F1Z5',
    registrationNumber: 'MH-LAB-2019-4421',
    supportedTests: ['LFT panel', 'CBC', 'Viral markers', 'Lipid profile'],
    legalDocuments: [
      {
        id: 'doc-lab-1-reg',
        label: 'Lab registration certificate',
        fileName: 'metro-diagnostics-registration.pdf',
        fileUrl: '/mock/pdf/legal/metro-registration.pdf',
        uploadedAt: days(180),
      },
      {
        id: 'doc-lab-1-gst',
        label: 'GST certificate',
        fileName: 'metro-diagnostics-gst.pdf',
        fileUrl: '/mock/pdf/legal/metro-gst.pdf',
        uploadedAt: days(180),
      },
    ],
    agreementDoc: {
      id: 'doc-lab-1-mou',
      label: 'Pathology tie-up agreement',
      fileName: 'metro-diagnostics-mou-2025.pdf',
      fileUrl: '/mock/pdf/legal/metro-mou-2025.pdf',
      uploadedAt: days(175),
    },
    reportFormatSample: {
      id: 'doc-lab-1-format',
      label: 'Sample report format',
      fileName: 'metro-report-sample.pdf',
      fileUrl: '/mock/pdf/legal/metro-report-sample.pdf',
      uploadedAt: days(170),
    },
    chargesPerTest: [
      { testName: 'LFT panel', chargeInr: 850 },
      { testName: 'CBC', chargeInr: 320 },
      { testName: 'Viral markers', chargeInr: 1200 },
      { testName: 'Lipid profile', chargeInr: 480 },
    ],
    packageCharges: 2200,
    annualTieupCharges: 120000,
    billingCycle: 'monthly',
    contractStart: '2025-04-01',
    contractEnd: '2026-03-31',
    active: true,
    notes: 'Primary partner for liver panels. Reports emailed to ops@livotale.test.',
    createdAt: days(180),
    updatedAt: days(30),
  },
  {
    id: 'lab-2',
    name: 'LifeCare Pathology',
    contactPerson: 'Ms. Neha Verma',
    phone: '9876500002',
    email: 'ops@lifecarepath.test',
    address: 'Koramangala 5th Block',
    city: 'Bangalore',
    state: 'Karnataka',
    pincode: '560095',
    gstNumber: '29AABCL5678G1Z2',
    registrationNumber: 'KA-LAB-2020-1188',
    supportedTests: ['LFT panel', 'HbA1c', 'Coagulation'],
    legalDocuments: [
      {
        id: 'doc-lab-2-reg',
        label: 'Lab registration certificate',
        fileName: 'lifecare-registration.pdf',
        fileUrl: '/mock/pdf/legal/lifecare-registration.pdf',
        uploadedAt: days(200),
      },
    ],
    agreementDoc: {
      id: 'doc-lab-2-mou',
      label: 'Pathology tie-up agreement',
      fileName: 'lifecare-mou-2025.pdf',
      fileUrl: '/mock/pdf/legal/lifecare-mou-2025.pdf',
      uploadedAt: days(195),
    },
    reportFormatSample: {
      id: 'doc-lab-2-format',
      label: 'Sample report format',
      fileName: 'lifecare-report-sample.pdf',
      fileUrl: '/mock/pdf/legal/lifecare-report-sample.pdf',
      uploadedAt: days(190),
    },
    chargesPerTest: [
      { testName: 'LFT panel', chargeInr: 780 },
      { testName: 'HbA1c', chargeInr: 450 },
      { testName: 'Coagulation', chargeInr: 650 },
    ],
    packageCharges: 1950,
    annualTieupCharges: 95000,
    billingCycle: 'quarterly',
    contractStart: '2025-01-01',
    contractEnd: '2025-12-31',
    active: true,
    notes: 'Bangalore coverage — secondary partner.',
    createdAt: days(200),
    updatedAt: days(60),
  },
];

/**
 * Child workflow demo orders (PKG-2/3 pathology):
 * - lco-7: lab assigned → collect blood (current)
 * - lco-8: blood collected → submit to lab (current)
 * - lco-9: awaiting lab email PDF → upload (current)
 * - lco-6: PDF uploaded → AI review (current)
 * - lco-2: letterhead generated (all steps done)
 * - lco-3: letterhead published + consult (all steps done)
 */
export const MOCK_SAMPLE_DISPATCHES: Record<string, SampleDispatch> = {
  'lco-7': {
    id: 'sd-lco-7',
    orderId: 'lco-7',
    partnerLabId: 'lab-2',
    partnerLabName: 'LifeCare Pathology',
    status: 'pending_dispatch',
    updatedAt: days(0),
  },
  'lco-8': {
    id: 'sd-lco-8',
    orderId: 'lco-8',
    partnerLabId: 'lab-1',
    partnerLabName: 'Metro Diagnostics',
    status: 'sample_collected',
    collectedBy: 'technician',
    collectedAt: days(0),
    orderLabelVerified: true,
    collectionPhotos: [
      {
        id: 'proof-lco-8-1',
        orderId: 'lco-8',
        photoType: 'order_id_label',
        fileName: 'lco-8-order-label.jpg',
        storageUrl: 'https://placehold.co/480x320/fdf2f8/be185d?text=LFS-2026-0008',
        createdAt: days(0),
      },
      {
        id: 'proof-lco-8-2',
        orderId: 'lco-8',
        photoType: 'sample_tube',
        fileName: 'lco-8-tube.jpg',
        storageUrl: 'https://placehold.co/480x320/fce7f3/be185d?text=Sample+tube',
        createdAt: days(0),
      },
      {
        id: 'proof-lco-8-3',
        orderId: 'lco-8',
        photoType: 'technician_collector',
        fileName: 'lco-8-tech.jpg',
        storageUrl: 'https://placehold.co/480x320/e0e7ff/4338ca?text=Technician',
        createdAt: days(0),
      },
    ],
    updatedAt: days(0),
  },
  'lco-9': {
    id: 'sd-lco-9',
    orderId: 'lco-9',
    partnerLabId: 'lab-1',
    partnerLabName: 'Metro Diagnostics',
    status: 'awaiting_report',
    collectedBy: 'technician',
    collectedAt: days(2),
    dispatchedBy: 'technician',
    dispatchedAt: days(2),
    receivedAtLabAt: days(1),
    awaitingReportSince: days(0),
    courierRef: 'COUR-MUM-5512',
    orderLabelVerified: true,
    collectionPhotos: [
      {
        id: 'proof-lco-9-1',
        orderId: 'lco-9',
        photoType: 'order_id_label',
        fileName: 'lco-9-label.jpg',
        storageUrl: 'https://placehold.co/480x320/fdf2f8/be185d?text=LFS-2026-0009',
        createdAt: days(2),
      },
      {
        id: 'proof-lco-9-2',
        orderId: 'lco-9',
        photoType: 'sample_tube',
        fileName: 'lco-9-tubes.jpg',
        storageUrl: 'https://placehold.co/480x320/fce7f3/be185d?text=Sample+tubes',
        createdAt: days(2),
      },
      {
        id: 'proof-lco-9-3',
        orderId: 'lco-9',
        photoType: 'technician_collector',
        fileName: 'lco-9-tech.jpg',
        storageUrl: 'https://placehold.co/480x320/e0e7ff/4338ca?text=Technician',
        createdAt: days(2),
      },
      {
        id: 'proof-lco-9-4',
        orderId: 'lco-9',
        photoType: 'lab_handover',
        fileName: 'lco-9-handover.jpg',
        storageUrl: 'https://placehold.co/480x320/dbeafe/1d4ed8?text=Lab+handover',
        createdAt: days(2),
      },
    ],
    updatedAt: days(0),
  },
  'lco-6': {
    id: 'sd-lco-6',
    orderId: 'lco-6',
    partnerLabId: 'lab-2',
    partnerLabName: 'LifeCare Pathology',
    status: 'report_uploaded',
    collectedBy: 'technician',
    collectedAt: days(4),
    dispatchedBy: 'technician',
    dispatchedAt: days(3),
    receivedAtLabAt: days(2),
    awaitingReportSince: days(2),
    courierRef: 'COUR-BLR-8892',
    notes: 'Lab confirmed receipt — report received via email.',
    updatedAt: days(1),
  },
  'lco-2': {
    id: 'sd-lco-2',
    orderId: 'lco-2',
    partnerLabId: 'lab-1',
    partnerLabName: 'Metro Diagnostics',
    status: 'report_uploaded',
    collectedBy: 'technician',
    collectedAt: days(6),
    dispatchedBy: 'operations',
    dispatchedAt: days(5),
    receivedAtLabAt: days(4),
    awaitingReportSince: days(4),
    orderLabelVerified: true,
    collectionPhotos: [
      {
        id: 'proof-lco-2-1',
        orderId: 'lco-2',
        photoType: 'order_id_label',
        fileName: 'lco-2-order-label.jpg',
        storageUrl: 'https://placehold.co/480x320/fdf2f8/be185d?text=LFS-2026-0002+label',
        createdAt: days(6),
      },
      {
        id: 'proof-lco-2-2',
        orderId: 'lco-2',
        photoType: 'sample_tube',
        fileName: 'lco-2-tubes.jpg',
        storageUrl: 'https://placehold.co/480x320/fce7f3/be185d?text=Sample+tubes',
        createdAt: days(6),
      },
      {
        id: 'proof-lco-2-3',
        orderId: 'lco-2',
        photoType: 'technician_collector',
        fileName: 'lco-2-tech.jpg',
        storageUrl: 'https://placehold.co/480x320/e0e7ff/4338ca?text=Technician',
        createdAt: days(6),
      },
      {
        id: 'proof-lco-2-4',
        orderId: 'lco-2',
        photoType: 'lab_handover',
        fileName: 'lco-2-handover.jpg',
        storageUrl: 'https://placehold.co/480x320/dbeafe/1d4ed8?text=Lab+handover',
        createdAt: days(5),
      },
    ],
    updatedAt: days(3),
  },
  'lco-3': {
    id: 'sd-lco-3',
    orderId: 'lco-3',
    partnerLabId: 'lab-1',
    partnerLabName: 'Metro Diagnostics',
    status: 'report_uploaded',
    collectedBy: 'technician',
    collectedAt: days(8),
    dispatchedBy: 'technician',
    dispatchedAt: days(7),
    receivedAtLabAt: days(6),
    awaitingReportSince: days(6),
    courierRef: 'COUR-MUM-4421',
    updatedAt: days(4),
  },
};

export const MOCK_LAB_REPORTS: Record<string, LabReportUpload> = {
  'lco-6': {
    id: 'lr-lco-6',
    orderId: 'lco-6',
    patientId: 'demo-patient-5',
    partnerLabId: 'lab-2',
    partnerLabName: 'LifeCare Pathology',
    fileName: 'kavita-nair-lft-report.pdf',
    fileUrl: '/mock/pdf/pathology/lco-6.pdf',
    fileId: 'file-lr-lco-6',
    uploadedBy: 'operations',
    uploadedAt: days(1),
    extractionStatus: 'review_pending',
    finalStatus: 'pending',
    sourceType: 'partner_lab_email',
    emailFrom: 'ops@lifecarepath.test',
    emailSubject: 'Pathology report — Kavita Nair',
  },
  'lco-2': {
    id: 'lr-lco-2',
    orderId: 'lco-2',
    patientId: 'demo-patient-3',
    partnerLabId: 'lab-1',
    partnerLabName: 'Metro Diagnostics',
    fileName: 'vikram-patel-lft-report.pdf',
    fileUrl: '/mock/pdf/pathology/lco-2.pdf',
    fileId: 'file-lr-lco-2',
    uploadedBy: 'operations',
    uploadedAt: days(3),
    extractionStatus: 'verified',
    finalStatus: 'verified',
    verifiedBy: 'operations',
    verifiedAt: days(2),
    sourceType: 'partner_lab_email',
    emailFrom: 'reports@metrodiag.test',
  },
  'lco-3': {
    id: 'lr-lco-3',
    orderId: 'lco-3',
    patientId: 'demo-patient-1',
    partnerLabId: 'lab-1',
    partnerLabName: 'Metro Diagnostics',
    fileName: 'anita-desai-lft-report.pdf',
    fileUrl: '/mock/pdf/pathology/lco-3.pdf',
    fileId: 'file-lr-lco-3',
    uploadedBy: 'operations',
    uploadedAt: days(4),
    extractionStatus: 'verified',
    finalStatus: 'verified',
    verifiedBy: 'operations',
    verifiedAt: days(3),
    sourceType: 'partner_lab_email',
    emailFrom: 'reports@metrodiag.test',
  },
};

export const MOCK_AI_JOBS: Record<string, AIExtractionJob> = {
  'lco-6': {
    id: 'ai-job-lco-6',
    orderId: 'lco-6',
    sourceType: 'pathology',
    sourceFileId: 'file-lr-lco-6',
    status: 'review_pending',
    fields: [
      { id: 'f6', fieldName: 'Hemoglobin', extractedValue: '11.9', editableValue: '11.9', unit: 'g/dL', referenceRange: '12.0–16.0', flag: 'low', confidenceScore: 0.89, sourcePage: 1, verified: false },
      { id: 'f7', fieldName: 'SGOT/AST', extractedValue: '55', editableValue: '55', unit: 'U/L', referenceRange: '10–40', flag: 'high', confidenceScore: 0.85, sourcePage: 2, verified: false },
      { id: 'f8', fieldName: 'SGPT/ALT', extractedValue: '48', editableValue: '48', unit: 'U/L', referenceRange: '7–56', flag: 'normal', confidenceScore: 0.87, sourcePage: 2, verified: false },
      { id: 'f9', fieldName: 'Total bilirubin', extractedValue: '1.1', editableValue: '1.1', unit: 'mg/dL', referenceRange: '0.2–1.2', flag: 'normal', confidenceScore: 0.92, sourcePage: 2, verified: false },
    ],
    createdAt: days(1),
    updatedAt: days(1),
  },
  'lco-2': {
    id: 'ai-job-lco-2',
    orderId: 'lco-2',
    sourceType: 'pathology',
    sourceFileId: 'file-lr-lco-2',
    status: 'verified',
    fields: [
      { id: 'f1', fieldName: 'Hemoglobin', extractedValue: '13.2', editableValue: '13.2', unit: 'g/dL', referenceRange: '12.0–16.0', flag: 'normal', confidenceScore: 0.94, sourcePage: 1, verified: true },
      { id: 'f2', fieldName: 'SGOT/AST', extractedValue: '42', editableValue: '42', unit: 'U/L', referenceRange: '10–40', flag: 'high', confidenceScore: 0.88, sourcePage: 2, verified: true },
      { id: 'f3', fieldName: 'SGPT/ALT', extractedValue: '38', editableValue: '38', unit: 'U/L', referenceRange: '7–56', flag: 'normal', confidenceScore: 0.9, sourcePage: 2, verified: true },
    ],
    verifiedBy: 'operations',
    verifiedAt: days(2),
    createdAt: days(3),
    updatedAt: days(2),
  },
  'lco-3': {
    id: 'ai-job-lco-3',
    orderId: 'lco-3',
    sourceType: 'pathology',
    sourceFileId: 'file-lr-lco-3',
    status: 'verified',
    fields: [
      { id: 'f4', fieldName: 'Hemoglobin', extractedValue: '12.8', editableValue: '12.8', unit: 'g/dL', referenceRange: '12.0–16.0', flag: 'normal', confidenceScore: 0.93, sourcePage: 1, verified: true },
      { id: 'f5', fieldName: 'Platelet count', extractedValue: '165000', editableValue: '165000', unit: '/µL', referenceRange: '150000–400000', flag: 'normal', confidenceScore: 0.91, sourcePage: 1, verified: true },
    ],
    verifiedBy: 'operations',
    verifiedAt: days(3),
    createdAt: days(4),
    updatedAt: days(3),
  },
};
