import type { PartnerLab } from '@/types/partnerLab';
import type { LabReportUpload } from '@/types/labReport';
import type { AIExtractionJob } from '@/types/aiExtraction';
import type { SampleDispatch } from '@/types/sampleDispatch';

const now = Date.now();
const days = (n: number) => new Date(now - n * 86400000).toISOString();

export const MOCK_PARTNER_LABS: PartnerLab[] = [
  {
    id: 'lab-1',
    name: 'Metro Diagnostics',
    contactPerson: 'Dr. Sanjay Rao',
    phone: '9876500001',
    email: 'reports@metrodiag.test',
    address: 'Andheri Kurla Road',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400069',
    gstNumber: '27AABCM1234F1Z5',
    registrationNumber: 'MH-LAB-2019-4421',
    supportedTests: ['LFT panel', 'CBC', 'Viral markers', 'Lipid profile'],
    annualTieupCharges: 120000,
    contractStart: '2025-04-01',
    contractEnd: '2026-03-31',
    active: true,
    notes: 'Primary partner for liver panels.',
    createdAt: days(180),
    updatedAt: days(30),
  },
  {
    id: 'lab-2',
    name: 'LifeCare Pathology',
    contactPerson: 'Ms. Neha Verma',
    phone: '9876500002',
    email: 'ops@lifecarepath.test',
    address: 'Koramangala 5th Block',
    city: 'Bangalore',
    state: 'Karnataka',
    pincode: '560095',
    gstNumber: '29AABCL5678G1Z2',
    registrationNumber: 'KA-LAB-2020-1188',
    supportedTests: ['LFT panel', 'HbA1c', 'Coagulation'],
    annualTieupCharges: 95000,
    contractStart: '2025-01-01',
    contractEnd: '2025-12-31',
    active: true,
    createdAt: days(200),
    updatedAt: days(60),
  },
];

export const MOCK_SAMPLE_DISPATCHES: Record<string, SampleDispatch> = {
  'lco-3': {
    id: 'sd-lco-3',
    orderId: 'lco-3',
    partnerLabId: 'lab-1',
    partnerLabName: 'Metro Diagnostics',
    status: 'report_uploaded',
    dispatchedBy: 'technician',
    dispatchedAt: days(6),
    receivedAtLabAt: days(5),
    awaitingReportSince: days(5),
    courierRef: 'COUR-MUM-4421',
    updatedAt: days(4),
  },
  'lco-2': {
    id: 'sd-lco-2',
    orderId: 'lco-2',
    partnerLabId: 'lab-1',
    partnerLabName: 'Metro Diagnostics',
    status: 'report_uploaded',
    dispatchedBy: 'operations',
    dispatchedAt: days(5),
    receivedAtLabAt: days(4),
    updatedAt: days(3),
  },
  'lco-6': {
    id: 'sd-lco-6',
    orderId: 'lco-6',
    partnerLabId: 'lab-2',
    partnerLabName: 'LifeCare Pathology',
    status: 'awaiting_report',
    dispatchedBy: 'technician',
    dispatchedAt: days(2),
    receivedAtLabAt: days(1),
    awaitingReportSince: days(1),
    courierRef: 'COUR-BLR-8892',
    notes: 'Lab confirmed receipt — report expected via email.',
    updatedAt: days(1),
  },
  'lco-5': {
    id: 'sd-lco-5',
    orderId: 'lco-5',
    partnerLabId: 'lab-1',
    partnerLabName: 'Metro Diagnostics',
    status: 'pending_dispatch',
    updatedAt: days(0),
  },
};

export const MOCK_LAB_REPORTS: Record<string, LabReportUpload> = {
  'lco-6': {
    id: 'lr-lco-6',
    orderId: 'lco-6',
    patientId: 'demo-patient-5',
    partnerLabId: 'lab-2',
    partnerLabName: 'LifeCare Pathology',
    fileName: 'kavita-nair-lft-report.pdf',
    fileUrl: '/mock/pdf/pathology/lco-6.pdf',
    fileId: 'file-lr-lco-6',
    uploadedBy: 'operations',
    uploadedAt: days(1),
    extractionStatus: 'review_pending',
    finalStatus: 'pending',
  },
  'lco-2': {
    id: 'lr-lco-2',
    orderId: 'lco-2',
    patientId: 'demo-patient-3',
    partnerLabId: 'lab-1',
    partnerLabName: 'Metro Diagnostics',
    fileName: 'vikram-patel-lft-report.pdf',
    fileUrl: '/mock/pdf/pathology/lco-2.pdf',
    fileId: 'file-lr-lco-2',
    uploadedBy: 'operations',
    uploadedAt: days(3),
    extractionStatus: 'verified',
    finalStatus: 'verified',
    verifiedBy: 'operations',
    verifiedAt: days(2),
  },
  'lco-3': {
    id: 'lr-lco-3',
    orderId: 'lco-3',
    patientId: 'demo-patient-1',
    partnerLabId: 'lab-1',
    partnerLabName: 'Metro Diagnostics',
    fileName: 'anita-desai-lft-report.pdf',
    fileUrl: '/mock/pdf/pathology/lco-3.pdf',
    fileId: 'file-lr-lco-3',
    uploadedBy: 'operations',
    uploadedAt: days(4),
    extractionStatus: 'verified',
    finalStatus: 'verified',
    verifiedBy: 'operations',
    verifiedAt: days(3),
  },
};

export const MOCK_AI_JOBS: Record<string, AIExtractionJob> = {
  'lco-6': {
    id: 'ai-job-lco-6',
    orderId: 'lco-6',
    sourceType: 'pathology',
    sourceFileId: 'file-lr-lco-6',
    status: 'review_pending',
    fields: [
      { id: 'f6', fieldName: 'Hemoglobin', extractedValue: '11.9', editableValue: '11.9', unit: 'g/dL', referenceRange: '12.0–16.0', flag: 'low', confidenceScore: 0.89, sourcePage: 1, verified: false },
      { id: 'f7', fieldName: 'SGOT/AST', extractedValue: '55', editableValue: '55', unit: 'U/L', referenceRange: '10–40', flag: 'high', confidenceScore: 0.85, sourcePage: 2, verified: false },
      { id: 'f8', fieldName: 'SGPT/ALT', extractedValue: '48', editableValue: '48', unit: 'U/L', referenceRange: '7–56', flag: 'normal', confidenceScore: 0.87, sourcePage: 2, verified: false },
      { id: 'f9', fieldName: 'Total bilirubin', extractedValue: '1.1', editableValue: '1.1', unit: 'mg/dL', referenceRange: '0.2–1.2', flag: 'normal', confidenceScore: 0.92, sourcePage: 2, verified: false },
    ],
    createdAt: days(1),
    updatedAt: days(1),
  },
  'lco-2': {
    id: 'ai-job-lco-2',
    orderId: 'lco-2',
    sourceType: 'pathology',
    sourceFileId: 'file-lr-lco-2',
    status: 'verified',
    fields: [
      { id: 'f1', fieldName: 'Hemoglobin', extractedValue: '13.2', editableValue: '13.2', unit: 'g/dL', referenceRange: '12.0–16.0', flag: 'normal', confidenceScore: 0.94, sourcePage: 1, verified: true },
      { id: 'f2', fieldName: 'SGOT/AST', extractedValue: '42', editableValue: '42', unit: 'U/L', referenceRange: '10–40', flag: 'high', confidenceScore: 0.88, sourcePage: 2, verified: true },
      { id: 'f3', fieldName: 'SGPT/ALT', extractedValue: '38', editableValue: '38', unit: 'U/L', referenceRange: '7–56', flag: 'normal', confidenceScore: 0.9, sourcePage: 2, verified: true },
    ],
    verifiedBy: 'operations',
    verifiedAt: days(2),
    createdAt: days(3),
    updatedAt: days(2),
  },
  'lco-3': {
    id: 'ai-job-lco-3',
    orderId: 'lco-3',
    sourceType: 'pathology',
    sourceFileId: 'file-lr-lco-3',
    status: 'verified',
    fields: [
      { id: 'f4', fieldName: 'Hemoglobin', extractedValue: '12.8', editableValue: '12.8', unit: 'g/dL', referenceRange: '12.0–16.0', flag: 'normal', confidenceScore: 0.93, sourcePage: 1, verified: true },
      { id: 'f5', fieldName: 'Platelet count', extractedValue: '165000', editableValue: '165000', unit: '/µL', referenceRange: '150000–400000', flag: 'normal', confidenceScore: 0.91, sourcePage: 1, verified: true },
    ],
    verifiedBy: 'operations',
    verifiedAt: days(3),
    createdAt: days(4),
    updatedAt: days(3),
  },
};
